---
- name: config monitoring server
  become: true
  hosts: monitoring

  tasks:
  - name: "Install and config Prometheus"
    include_role:
      name: prometheus

  - name: "Install and config Node Exporter"
    include_role:
      name: node_exporter

  - name: "Install and config EK"
    include_role:
      name: ek

  - name: "Install and config fluentbit"
    include_role:
      name: fluentbit